In [4]:
import pandas as pd

# Series

1차원 배열 만들기가 목표

In [11]:
import numpy as np
arr = np.arange(100, 110) #0배열 기준을 일반 기준으로 보면 100이상 110미만 범위
print(arr)

[100 101 102 103 104 105 106 107 108 109]


In [13]:
s = pd.Series(arr)
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64


In [14]:
s = pd.Series(arr, dtype='int32')
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int32


In [16]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)
print(s)

0     kim
1     lee
2    park
3    hong
dtype: object


In [20]:
s = pd.Series([1, 2, 3, 5, '99'])
print(s)

0     1
1     2
2     3
3     5
4    99
dtype: object


# indexing

In [26]:
person = ['kim', 'lee', 'park', 'hong']
s= pd.Series(person)

In [27]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [28]:
s[2]

'park'

In [29]:
s[-1]

KeyError: -1

In [31]:
s = pd.Series(person, index=['a', 'b', 'c', 'd'])
print(s)

a     kim
b     lee
c    park
d    hong
dtype: object


In [32]:
s['a']

'kim'

In [33]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [34]:
s.values

array(['kim', 'lee', 'park', 'hong'], dtype=object)

In [35]:
s.ndim

1

In [37]:
s.shape

(4,)

### NaN(Not a Number)

결측치

In [40]:
s = pd.Series(person + [np.nan])
print(s) #NaN이라는 빠진 데이터(결측치)가 있는지 확인해보는 것

0     kim
1     lee
2    park
3    hong
4     NaN
dtype: object


In [50]:
arr = np.arange(50, 55)
s = pd.Series(arr, dtype='float32')
print(s)

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float32


In [96]:
f = ['바나나', np.nan, '사과', '포도', '복숭아']
s = pd.Series(f, index=list('가나다라마'))
print(s)

가    바나나
나    NaN
다     사과
라     포도
마    복숭아
dtype: object


In [97]:
s[['가', '나']]

가    바나나
나    NaN
dtype: object

# bool

In [98]:
s[[True, False, True, False, True]]

가    바나나
다     사과
마    복숭아
dtype: object

In [99]:
a = [True, False, True, False, True]
s[a]

가    바나나
다     사과
마    복숭아
dtype: object

In [100]:
arr = np.arange(5, 20)
s = pd.Series(arr)
print(s)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64


In [101]:
s < 10

0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [102]:
s[s < 10]

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [103]:
s[s == 5]

0    5
dtype: int64

# 결측치 처리

이해가 잘 안되네


In [87]:
s = pd.Series([2, 5, 2, 1, np.nan, 2, 4, 9, np.nan])

In [88]:
s.isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [89]:
s[s.isnull()]

4   NaN
8   NaN
dtype: float64

In [90]:
s. isna()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [91]:
s[s.isna()]

4   NaN
8   NaN
dtype: float64

In [92]:
s[s.notnull()]

0    2.0
1    5.0
2    2.0
3    1.0
5    2.0
6    4.0
7    9.0
dtype: float64

# dataframe

In [106]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [110]:
df = pd.DataFrame(arr)
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [114]:
df = pd.DataFrame(arr, columns=['가', '나', '다',], index=['a', 'b', 'c'])
df

가  나  다
a  0  1  2
b  3  4  5
c  6  7  8

In [122]:
data = { 
    'name': ['kim', 'lee', 'park'],
    'age': [10, 15, 20],
    'location': ['seoul','LA', 'tokyo']
}
df = pd.DataFrame(data)
df

name  age location
0   kim   10    seoul
1   lee   15       LA
2  park   20    tokyo

In [123]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [124]:
df.columns

Index(['name', 'age', 'location'], dtype='object')

In [125]:
df.dtypes

name        object
age          int64
location    object
dtype: object

In [127]:
df.T

0    1      2
name        kim  lee   park
age          10   15     20
location  seoul   LA  tokyo

In [129]:
df.index = list('abc')

#다음과정 뭐지? 놓침

# column

In [131]:
df['name']

a     kim
b     lee
c    park
Name: name, dtype: object

In [132]:
type(df['name'])

pandas.core.series.Series

In [134]:
df[['name', 'location']]

name location
a   kim    seoul
b   lee       LA
c  park    tokyo

In [135]:
type(df[['name', 'location']])

pandas.core.frame.DataFrame

In [148]:
df.rename(column={'location': 'hometown'}, inplace=True)
df

AttributeError: 'NoneType' object has no attribute 'rename'